# On PR toward `main`: run builds, run tests

when:
  - event: manual
  - event: pull_request
    branch: main

steps:
  test_node:
    name: Tests
    image: node:18
    commands:
      - npm ci
      - npm run build
      - npm test
