name: Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test_node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check that build succeeds
        run: npm run build

      - name: Run unit tests
        run: npm test

  test_bun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun
        uses: antongolub/action-setup-bun@v1.13.1
        with:
          bun-version: 1.0.2
          cache: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check that build succeeds
        run: bun run build

      - name: Run unit tests
        run: bun test
