name: Check Versions Match

# On PR to main, check that package.json and package-lock.json share the version, and that CHANGELOG.md is spec-compliant. Block otherwise.

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun
        uses: antongolub/action-setup-bun@v1.13.1
        with:
          bun-version: 1.0.2
          cache: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check versions Match
        run: bun ./scripts/release.ts
